name: Version
on:
  push:
    branches: [main]

env:
  simba-download: https://github.com/Villavu/Simba/releases/download/simba1400-release/Simba-Win32.exe
  srl-download: https://github.com/Torwent/SRL-T.git

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Torwent/setup-simba@master

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Compile test
        shell: bash
        run: |
          cd ..
          ./Simba.exe --compile test.simba