name: Version
on:
  push:
    branches: [main]

env:
  simba-download: https://github.com/Villavu/Simba/releases/download/simba1400-release/Simba-Win32.exe
  srl-download: https://github.com/Torwent/SRL-T.git

jobs:
  compile:
    runs-on: windows-latest
    steps:
      - uses: Torwent/setup-simba@master          
      - uses: actions/checkout@v4
        with:
          path: Simba/Scripts
     
      - name: Compile test
        shell: bash
        run: |
          cd Simba
          ./Simba.exe --compile Scripts/launcher/launcher.simba
          
      - name: S2SCompiler
        shell: bash
        run: |
          cd Simba
          ./Simba.exe --run --path Scripts/launcher/launcher/ --output Scripts/ Includes/WaspLib/tools/s2scompiler.simba
          cd Scripts
        
      - name: Generate changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.18.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-message: "chore(release): {version}"
          preset: "angular"
          tag-prefix: "v"
          output-file: "CHANGELOG.md"
          skip-version-file: "true"
          skip-on-empty: "true"
          skip-commit: "true"
      
      - name: Commit and push changes
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: |
          git config --global user.name 'WaspBot'
          git config --global user.email 'wasp@waspscripts.com'
          git commit -am "chore: github action"
          git push
          
      - name: Create release
        uses: actions/create-release@v1.1.4
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}